//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6CodeFirstMPLIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_KHUVUC
    {
        
        public DC_KHUVUC()
        {
            this.DC_THUADAT = new HashSet<DC_THUADAT>();
        }
    
        public string KHUVUCID { get; set; }
        public string TENKHUVUC { get; set; }
        public string XAID { get; set; }
    
        
        public virtual ICollection<DC_THUADAT> DC_THUADAT { get; set; }
        public virtual HC_DMKVHC HC_DMKVHC { get; set; }
    }
}
