//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6CodeFirstMPLIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_LOAINGHIAVUTAICHINH
    {
        
        public DC_LOAINGHIAVUTAICHINH()
        {
            this.DC_NGHIAVUTAICHINH = new HashSet<DC_NGHIAVUTAICHINH>();
        }
    
        public string LOAINGHIAVUTAICHINHID { get; set; }
        public string TENLOAINGHIAVUTAICHINH { get; set; }
        public string uId { get; set; }
        public Nullable<System.DateTime> THOIDIEMKHOITAO { get; set; }
        public string NGUOICAPNHATID { get; set; }
        public Nullable<System.DateTime> THOIDIEMCAPNHAT { get; set; }
    
        
        public virtual ICollection<DC_NGHIAVUTAICHINH> DC_NGHIAVUTAICHINH { get; set; }
    }
}
