//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6CodeFirstMPLIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAIDTMIENGIAM
    {
        
        public DM_LOAIDTMIENGIAM()
        {
            this.DC_GCN_TILESH = new HashSet<DC_GCN_TILESH>();
            this.DC_MIENGIAMNVTC = new HashSet<DC_MIENGIAMNVTC>();
        }
    
        public string LOAIDTMIENGIAMID { get; set; }
        public string TENLOAIDOITUONG { get; set; }
        public string GHICHU { get; set; }
    
        
        public virtual ICollection<DC_GCN_TILESH> DC_GCN_TILESH { get; set; }
        
        public virtual ICollection<DC_MIENGIAMNVTC> DC_MIENGIAMNVTC { get; set; }
    }
}
